# Generated by Django 3.2 on 2024-11-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProfesor', '0003_auto_20241111_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
