# Generated by Django 3.2 on 2024-11-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProfesor', '0004_auto_20241112_1356'),
        ('appAlumno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('horas', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('seccion', models.CharField(max_length=20)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProfesor.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=30),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAlumno.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAlumno.curso')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(through='appAlumno.Matricula', to='appAlumno.Curso'),
        ),
    ]
