# Generated by Django 3.2 on 2024-11-12 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProfesor', '0003_auto_20241111_2318'),
        ('appAlumno', '0002_auto_20241025_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('horas', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('seccion', models.PositiveIntegerField()),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProfesor.profesor')),
            ],
        ),
    ]
