# Generated by Django 3.2 on 2024-11-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAlumno', '0003_auto_20241111_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='seccion',
            field=models.CharField(max_length=20),
        ),
    ]
