# Generated by Django 3.2 on 2024-11-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAlumno', '0005_alumno_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(to='appAlumno.Curso'),
        ),
    ]
