# Generated by Django 3.2 on 2024-11-12 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAlumno', '0005_alumno_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='nombre',
        ),
    ]
