# Generated by Django 3.2 on 2024-11-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAlumno', '0006_alumno_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
