# Generated by Django 3.2 on 2024-11-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAlumno', '0006_remove_alumno_nombre'),
        ('appAlumno', '0007_alter_alumno_nombre'),
    ]

    operations = [
    ]
